services:
  movies-service:
    image: movies-service:0.0.1
    env_file:
      - .env.properties
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - movies-service-db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movies-service-db/movie-service-db
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}

  movies-service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: movie-service-db
    ports:
      - "5433:5432"
    volumes:
      - movie-service-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  movie-service-db-data: