spring:
  config:
    import: optional:file:.env.properties
  application:
    name: movies-service
  datasource:
    url: jdbc:postgresql://localhost:5433/movie-service-db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    show-sql: false
    open-in-view: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

property:
  app:
    kino-poisk-api-key: ${KINO-POISK-API-KEY}