name: Deploy Movies Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          APP_DIR=~/movies-service

          # If directory exists, update; otherwise, clone
          if [ -d "$APP_DIR" ]; then
            cd $APP_DIR
            git pull
          else
            git clone https://github.com/CineMatchTogether/movies-service.git $APP_DIR
            cd $APP_DIR
          fi

          # Copy .env file (update the path to the local .env if necessary)
          echo "$ENV_FILE_CONTENT" > $APP_DIR/.env

          # Restart Docker Compose
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
          EOF
